"use client";

import { useEffect, useState } from "react";
import { Activity, CircleCheck, CircleX, Cpu, KeyRound, Zap } from "lucide-react";

const apiBase = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Status = { current_provider: string; current_model: string; fallback_provider: string; default_provider: string };
type Health = { provider: string; provider_name?: string; healthy: boolean; configured: boolean; connected: boolean; available_models: string[]; latency_ms: number; default_provider: boolean; reason: string; model?: string; last_error?: string };

function providerState(item: Health) { if (!item.configured) return "Not configured"; if (item.healthy && item.connected) return "Connected"; if (item.reason?.toLowerCase().includes("quota")) return "Quota exceeded"; return "Offline"; }

export default function ProvidersPage() {
    const [status, setStatus] = useState<Status | null>(null);
    const [health, setHealth] = useState<Health[]>([]);
    const [error, setError] = useState<string | null>(null);
    useEffect(() => { Promise.all([fetch(`${apiBase}/providers/status`).then((response) => response.json() as Promise<Status>), fetch(`${apiBase}/providers/health`).then((response) => response.json() as Promise<Health[]>)]).then(([loadedStatus, loadedHealth]) => { setStatus(loadedStatus); setHealth(loadedHealth); }).catch((reason: Error) => setError(reason.message)); }, []);
    return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100 lg:px-12"><div className="mx-auto max-w-7xl"><header className="border-b border-white/10 pb-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300">Provider control</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">AI provider routing</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Observe the active model, connection state, latency, and fallback path without changing the existing verification dashboard.</p></header>{error ? <p className="mt-8 text-sm text-rose-300">{error}</p> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="border border-cyan-300/20 bg-cyan-300/[0.05] p-5"><Zap className="h-5 w-5 text-cyan-300" /><p className="mt-5 text-xs uppercase tracking-wider text-slate-500">Current provider</p><p className="mt-2 text-xl font-semibold">{status?.current_provider ?? "local-mock"}</p></div><div className="border border-white/10 bg-white/[0.03] p-5"><Cpu className="h-5 w-5 text-violet-300" /><p className="mt-5 text-xs uppercase tracking-wider text-slate-500">Current model</p><p className="mt-2 truncate text-xl font-semibold">{status?.current_model ?? "mock-model"}</p></div><div className="border border-white/10 bg-white/[0.03] p-5"><KeyRound className="h-5 w-5 text-amber-300" /><p className="mt-5 text-xs uppercase tracking-wider text-slate-500">Default provider</p><p className="mt-2 text-xl font-semibold">{status?.default_provider ?? "gemini"}</p></div><div className="border border-white/10 bg-white/[0.03] p-5"><Activity className="h-5 w-5 text-emerald-300" /><p className="mt-5 text-xs uppercase tracking-wider text-slate-500">Fallback</p><p className="mt-2 text-xl font-semibold">{status?.fallback_provider ?? "local-mock"}</p></div></section><section className="mt-6 border border-white/10 bg-white/[0.03] p-6"><h2 className="font-semibold">Provider health</h2><div className="mt-5 divide-y divide-white/10">{health.map((item) => <div key={item.provider} className="grid gap-3 py-4 md:grid-cols-[1.2fr_1fr_1fr_1fr] md:items-center"><div className="flex items-center gap-3">{item.connected ? <CircleCheck className="h-4 w-4 text-emerald-300" /> : <CircleX className="h-4 w-4 text-slate-500" />}<div><p className="font-medium">{item.provider}{item.default_provider && <span className="ml-2 text-[10px] uppercase tracking-wider text-cyan-300">default</span>}</p><p className="text-xs text-slate-500">{item.reason || item.last_error || "Ready for gateway routing"}</p></div></div><span className={`text-sm ${item.healthy ? "text-emerald-300" : "text-amber-300"}`}>{providerState(item)}</span><span className="text-sm text-slate-400">{item.model ?? item.available_models[0] ?? "mock-model"}</span><span className="font-mono text-sm text-slate-400">{item.latency_ms.toFixed(1)} ms</span></div>)}</div></section></>}</div></main>;
}
