"use client";

import type { ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import { Check, ChevronRight, Loader2, Search, ShieldCheck } from "lucide-react";

export function AppShell({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-transparent">{children}</div>; }
export function TopNavigation({ children }: { children?: ReactNode }) { return <div className="flex items-center justify-between gap-4">{children}</div>; }
export function Sidebar({ children }: { children?: ReactNode }) { return <aside className="hidden w-60 shrink-0 lg:block">{children}</aside>; }
export function CommandPalette({ open, children }: { open: boolean; children?: ReactNode }) { return open ? <div className="fixed inset-0 z-50 flex items-start justify-center bg-slate-950/70 px-4 pt-24 backdrop-blur-sm">{children}</div> : null; }
export function SearchBar({ placeholder = "Search", value, onChange }: { placeholder?: string; value?: string; onChange?: (value: string) => void }) { return <label className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-sm text-slate-400"><Search className="h-4 w-4" /><input aria-label={placeholder} value={value} onChange={(event) => onChange?.(event.target.value)} placeholder={placeholder} className="min-w-0 bg-transparent outline-none placeholder:text-slate-600" /></label>; }
export function NotificationCenter({ count = 0 }: { count?: number }) { return <span className="relative inline-flex h-8 min-w-8 items-center justify-center rounded-lg border border-white/10 bg-white/[0.04] text-xs text-slate-300" aria-label={`${count} notifications`}>{count > 0 ? count : ""}</span>; }
export function UserMenu({ label = "Operator" }: { label?: string }) { return <button type="button" className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-xs font-semibold text-slate-300"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-violet-500/20 text-violet-200">{label.slice(0, 1)}</span>{label}</button>; }
export function MetricCard({ label, value, icon: Icon, trend }: { label: string; value: string; icon?: LucideIcon; trend?: string }) { return <article className="rounded-2xl border border-white/[0.08] bg-[#101828] p-5 transition hover:-translate-y-0.5 hover:border-violet-400/30">{Icon && <Icon className="h-5 w-5 text-violet-300" />}<p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p>{trend && <p className="mt-2 text-xs text-emerald-300">{trend}</p>}</article>; }
export function GlassCard({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/10 bg-white/[0.045] p-5 shadow-[0_18px_50px_rgba(0,0,0,0.14)] backdrop-blur-xl ${className}`}>{children}</section>; }
export function Timeline({ items }: { items: { title: string; detail?: string; status?: string }[] }) { return <div className="space-y-4">{items.map((item, index) => <div key={`${item.title}-${index}`} className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-violet-400" /><div><p className="text-sm font-semibold text-slate-200">{item.title}</p>{item.detail && <p className="mt-1 text-xs text-slate-500">{item.detail}</p>}{item.status && <p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{item.status}</p>}</div></div>)}</div>; }
export function PipelineStepper({ steps, current }: { steps: string[]; current?: number }) { return <div className="flex items-center overflow-x-auto">{steps.map((step, index) => <div key={step} className="flex items-center"><div className={`flex h-8 min-w-8 items-center justify-center rounded-full border px-2 text-[10px] font-bold ${index < (current ?? -1) ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : index === current ? "border-violet-400/40 bg-violet-500/20 text-violet-200" : "border-white/10 text-slate-600"}`}>{index < (current ?? -1) ? <Check className="h-3.5 w-3.5" /> : index + 1}</div>{index < steps.length - 1 && <ChevronRight className="mx-2 h-3.5 w-3.5 text-slate-700" />}</div>)}</div>; }
export function ExecutionProgress({ progress, label }: { progress: number; label: string }) { return <div><div className="flex justify-between text-xs text-slate-400"><span>{label}</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all duration-500" style={{ width: `${Math.max(0, Math.min(100, progress))}%` }} /></div></div>; }
export function StatusBadge({ label, tone = "neutral" }: { label: string; tone?: "success" | "warning" | "error" | "neutral" }) { const classes = { success: "bg-emerald-400/10 text-emerald-300", warning: "bg-amber-400/10 text-amber-300", error: "bg-rose-400/10 text-rose-300", neutral: "bg-white/[0.06] text-slate-300" }; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider ${classes[tone]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{label}</span>; }
export function ActivityFeed({ children }: { children: ReactNode }) { return <div className="space-y-3">{children}</div>; }
export function RepositoryCard({ children }: { children: ReactNode }) { return <GlassCard>{children}</GlassCard>; }
export function RepositoryHealthCard({ score, recommendations = [] }: { score: number; recommendations?: string[] }) { return <GlassCard><div className="flex items-center gap-4"><HealthGauge value={score} /><div><p className="text-sm font-semibold text-white">Repository health</p><p className="mt-1 text-xs text-slate-500">{recommendations[0] ?? "No recommendations available."}</p></div></div></GlassCard>; }
export function AIInsightCard({ title = "AI insight", children }: { title?: string; children: ReactNode }) { return <GlassCard><div className="flex items-center gap-2 text-violet-200"><SparkleIcon /><span className="text-xs font-semibold uppercase tracking-wider">{title}</span></div><div className="mt-4">{children}</div></GlassCard>; }
export function ConfidenceGauge({ value }: { value: number }) { return <HealthGauge value={value} label="Confidence" color="cyan" />; }
export function HealthGauge({ value, label = "Health", color = "green" }: { value: number; label?: string; color?: "green" | "cyan" }) { const tone = color === "cyan" ? "text-cyan-300 border-cyan-400/30" : "text-emerald-300 border-emerald-400/30"; return <div className={`flex h-20 w-20 shrink-0 flex-col items-center justify-center rounded-full border-8 ${tone}`}><span className="text-lg font-bold">{Math.round(value)}</span><span className="text-[9px] uppercase tracking-wider opacity-70">{label}</span></div>; }
export function PatchCard({ children }: { children: ReactNode }) { return <GlassCard>{children}</GlassCard>; }
export function VerificationCard({ children }: { children: ReactNode }) { return <GlassCard>{children}</GlassCard>; }
export function ExecutionLogViewer({ content = "", onCopy }: { content?: string; onCopy?: () => void }) { return <div className="overflow-hidden rounded-xl border border-white/10 bg-slate-950"><div className="flex items-center justify-between border-b border-white/10 px-3 py-2 text-[10px] uppercase tracking-wider text-slate-500"><span>Execution log</span><button type="button" onClick={onCopy} className="hover:text-white">Copy</button></div><pre className="max-h-72 overflow-auto p-4 font-mono text-xs leading-5 text-slate-300">{content || "Logs will appear after the next execution."}</pre></div>; }
export function DiffViewer({ diff = "" }: { diff?: string }) { return <pre className="max-h-96 overflow-auto rounded-xl border border-white/10 bg-slate-950 p-4 font-mono text-xs leading-5 text-slate-300">{diff || "Patch evidence will appear when a change is recommended."}</pre>; }
export function QuickActionPanel({ children }: { children: ReactNode }) { return <div className="grid gap-3 sm:grid-cols-2">{children}</div>; }
export function LoadingSkeleton({ className = "h-5 w-full" }: { className?: string }) { return <div className={`animate-pulse rounded-lg bg-white/[0.08] ${className}`} aria-label="Loading" />; }
export function EmptyState({ icon: Icon = ShieldCheck, title = "Evidence is loading", description = "The next verification signal will populate this view." }: { icon?: LucideIcon; title?: string; description?: string }) { return <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-white/10 px-6 py-10 text-center"><Icon className="h-6 w-6 text-slate-600" /><p className="mt-3 text-sm font-semibold text-slate-300">{title}</p><p className="mt-1 text-xs text-slate-600">{description}</p></div>; }
function SparkleIcon() { return <Loader2 className="h-4 w-4" />; }
