"use client";

import Link from "next/link";
import {
    Activity, AlertTriangle, ArrowUpRight, Box, CheckCircle2, Clock3,
    Code2, Database, FileCode2, FileText, FolderGit2, Gauge, GitBranch,
    Layers3, Package, Play, RefreshCw, RotateCcw, ShieldAlert, ShieldCheck,
    Sparkles, Terminal, Timer, Upload, Wrench, XCircle,
} from "lucide-react";
import type { ExecutionEvent, FinalVerificationReport, RepositoryAIAnalysis, RepositoryMetadata, TimelineEntry } from "@/types";
import { GlobalStatusBar } from "@/components/layout/GlobalStatusBar";
import { SectionCard } from "@/components/ui/SectionCard";
import { StatCard } from "@/components/ui/StatCard";
import { StatusChip } from "@/components/ui/StatusChip";
import { ExecutionMonitor } from "@/components/dashboard/ExecutionMonitor";
import { LogsPanel } from "@/components/dashboard/LogsPanel";
import { ProgressTimeline } from "@/components/dashboard/ProgressTimeline";
import { RecentProjectsCard } from "@/components/cards/RecentProjectsCard";
import { VerificationResultPanel } from "@/components/dashboard/VerificationResultPanel";
import { LoadingSpinner } from "@/components/ui/LoadingSpinner";
import { AIInsightCard, ExecutionProgress, GlassCard, PatchCard, QuickActionPanel, RepositoryCard, Timeline, VerificationCard } from "@/components/ui/EnterprisePrimitives";
import { EnhancedPipeline } from "@/components/dashboard/EnhancedPipeline";
import { RepositoryExplorer } from "@/components/dashboard/RepositoryExplorer";
import { AIThinkingPanel } from "@/components/dashboard/AIThinkingPanel";
import { ConfidenceGauge } from "@/components/dashboard/ConfidenceGauge";
import { TerminalExecutionLogs } from "@/components/dashboard/TerminalExecutionLogs";
import { AnimatedKPICard } from "@/components/ui/AnimatedKPICard";

const unavailable = "Not Available";
const pipeline = [
    ["Upload", "REPOSITORY_UPLOADED"], ["Repository Scan", "REPOSITORY_ANALYSIS_COMPLETE"],
    ["Dependency Check", "DEPENDENCY_DETECTION"], ["Sandbox", "SANDBOX_CREATED"],
    ["Execution", "EXECUTION_STARTED"], ["AI Diagnosis", "AI_ANALYSIS"],
    ["Patch Generator", "PATCH_GENERATED"], ["Self Healing", "RERUN"], ["Final Report", "VERIFICATION_READY"],
] as const;

interface CommandCenterProps {
    repository: RepositoryMetadata | null;
    analysis: RepositoryAIAnalysis | null;
    report: FinalVerificationReport | null;
    events: ExecutionEvent[];
    executionStatus: string;
    currentStage: string;
    progress: number;
    elapsedSeconds: number;
    isRunning: boolean;
    onStart: () => void;
    timeline: TimelineEntry[];
    uploads: import("@/types").UploadSummary[];
    uploadsLoading: boolean;
    repositoryLoading: boolean;
    analysisLoading: boolean;
    healthLoading: boolean;
    repositoryError: string | null;
    analysisError: string | null;
    onRefresh: () => void;
}

export function CommandCenter({ repository, analysis, report, events, executionStatus, currentStage, progress, elapsedSeconds, isRunning, onStart, timeline, uploads, uploadsLoading, repositoryLoading, analysisLoading, healthLoading, repositoryError, analysisError, onRefresh }: CommandCenterProps) {
    const rootCause = report?.troubleshooting?.root_cause ?? unavailable;
    const patch = report?.applied_patch ?? report?.generated_patch;
    const executionSuccess = report?.execution?.success;
    const dependencyFiles = repository?.important_files.filter((file) => ["requirements.txt", "pyproject.toml", "setup.py", "environment.yml"].includes(file.split("/").at(-1) ?? "")) ?? [];
    const activity = [...events.map((event) => ({ label: event.stage.replaceAll("_", " "), detail: event.message, status: event.status, timestamp: event.timestamp })), ...(report?.execution_history ?? []).map((entry) => ({ label: `Attempt ${entry.attempt_number}`, detail: entry.reason, status: entry.execution_status, timestamp: entry.timestamp }))];

    return <div className="mx-auto flex max-w-[1480px] lg:min-h-[calc(100vh-9rem)]"><aside className="hidden w-60 shrink-0 lg:block"><div className="sticky top-24"><CommandSidebar /></div></aside><main className="min-w-0 flex-1 px-4 py-8 sm:px-6 lg:px-10">
        <header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-violet-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> AI command center</div><h1 className="mt-3 text-4xl font-semibold tracking-[-0.03em] text-white">Reproducibility control plane</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Operate repository verification, failure diagnosis, and self-healing from one evidence-led workspace.</p></div><button type="button" onClick={onRefresh} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-semibold text-slate-200 hover:border-violet-400/40 hover:bg-violet-500/10"><RefreshCw className="h-4 w-4" /> Refresh workspace</button></header>
        <GlobalStatusBar repository={repository} analysis={analysis} report={report} executionStatus={friendlyStatus(executionStatus, isRunning)} />
        <KpiGrid repository={repository} analysis={analysis} report={report} elapsedSeconds={elapsedSeconds} />
        <SectionCard eyebrow="Verification engine" title="Verification pipeline" className="mb-6"><EnhancedPipeline events={events} report={report} currentStage={currentStage} /></SectionCard>
        <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr] mb-6"><RepositoryExplorer repository={repository} analysis={analysis} loading={repositoryLoading} /><AIThinkingPanel report={report} analysis={analysis} /></div>
        <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr] mb-6"><SectionCard eyebrow="Runtime evidence" title="Execution monitor" action={<StatusChip label={friendlyStatus(executionStatus, isRunning)} tone={statusTone(executionStatus, isRunning)} />}><ExecutionProgress progress={progress} label={currentStage} /><div className="mt-5"><ExecutionMonitor repositoryId={repository?.repository_id} events={events} status={executionStatus} currentStage={currentStage} progress={progress} elapsedSeconds={elapsedSeconds} isRunning={isRunning} onStart={onStart} /></div></SectionCard><SectionCard eyebrow="Evidence trail" title="Execution timeline"><ExecutionTimeline events={events} history={report?.execution_history ?? []} /></SectionCard></div>
        <VerificationCard><VerificationResultPanel report={report} error={report ? null : "Run verification to generate a final report."} /></VerificationCard>
        <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr] mb-6"><PatchSummary patch={patch} /><SectionCard eyebrow="Workspace activity" title="Recent activity"><ActivityFeed items={activity} /></SectionCard></div>
        <div className="grid gap-6 xl:grid-cols-[1fr_1fr] mb-6"><SectionCard eyebrow="Repository history" title="Recent projects"><RecentProjectsCard uploads={uploads} isLoading={uploadsLoading} /></SectionCard><SectionCard eyebrow="Operator tools" title="Quick actions"><QuickActions repositoryId={repository?.repository_id} onRun={onStart} isRunning={isRunning} /></SectionCard></div>
        <SectionCard eyebrow="Operational totals" title="Footer statistics"><FooterStats repository={repository} analysis={analysis} report={report} uploads={uploads} /></SectionCard>
        {(analysisError || repositoryError || healthLoading || analysisLoading) && <div className="mt-6 flex items-center gap-2 text-xs text-slate-500">{(analysisError || repositoryError) && <AlertTriangle className="h-4 w-4 text-amber-400" />}{analysisError ?? repositoryError ?? (healthLoading ? "Refreshing health signals..." : "Refreshing AI analysis...")}</div>}
    </main></div>;
}

function CommandSidebar() { return <nav className="border-r border-white/[0.07] py-5 pr-5"><p className="mb-4 px-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-600">Control plane</p><div className="space-y-1"><SidebarItem icon={Gauge} label="Overview" active /><SidebarItem icon={Upload} label="Uploads" href="#uploads" /><SidebarItem icon={Terminal} label="Execution" href="#execution" /><SidebarItem icon={Sparkles} label="AI insights" href="#insights" /><SidebarItem icon={FileText} label="Reports" href="/troubleshooting" /></div><div className="mt-10 rounded-2xl border border-violet-400/20 bg-violet-500/[0.08] p-4"><p className="text-xs font-semibold text-violet-200">Evidence first</p><p className="mt-2 text-xs leading-5 text-slate-400">Every score links back to repository metadata or a captured execution artifact.</p></div></nav>; }
function SidebarItem({ icon: Icon, label, href = "/dashboard", active = false }: { icon: typeof Gauge; label: string; href?: string; active?: boolean }) { return <Link href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${active ? "bg-violet-500/15 text-violet-200" : "text-slate-500 hover:bg-white/[0.05] hover:text-slate-200"}`}><Icon className="h-4 w-4" />{label}</Link>; }

function KpiGrid({ repository, analysis, report, elapsedSeconds }: { repository: RepositoryMetadata | null; analysis: RepositoryAIAnalysis | null; report: FinalVerificationReport | null; elapsedSeconds: number }) { const patchSuccess = report?.applied_patch && report.execution.success ? "100%" : report?.applied_patch ? "0%" : unavailable; const values = [{ label: "Repository health", value: repository ? `${repository.health_score}/100` : unavailable, icon: Gauge, tone: "violet" as const, description: "Structural readiness" }, { label: "AI confidence", value: report ? `${report.confidence}%` : unavailable, icon: Sparkles, tone: "cyan" as const, description: "Final verification signal" }, { label: "Execution success", value: report ? (report.execution.success ? "Success" : "Failed") : unavailable, icon: CheckCircle2, tone: report?.execution.success ? "green" as const : "amber" as const, description: "Latest captured run" }, { label: "Patch success", value: patchSuccess, icon: Wrench, tone: "green" as const, description: "Validated self-healing" }, { label: "Risk score", value: analysis ? `${analysis.risk_score}/100` : unavailable, icon: ShieldAlert, tone: "amber" as const, description: "Static risk model" }, { label: "Files analysed", value: repository ? String(repository.total_files) : unavailable, icon: FileCode2, tone: "violet" as const, description: "Repository scope" }, { label: "Dependencies", value: repository ? String(repository.important_files.filter((file) => /requirements|pyproject|setup|environment/.test(file)).length) : unavailable, icon: Package, tone: "cyan" as const, description: "Manifests detected" }, { label: "Issues found", value: analysis ? String(analysis.issues.length) : unavailable, icon: AlertTriangle, tone: analysis?.issues.length ? "amber" as const : "green" as const, description: "AI findings" }, { label: "Execution time", value: executionTimeLabel(report, elapsedSeconds), icon: Timer, tone: "cyan" as const, description: "Captured duration" }, { label: "Datasets", value: repository ? String(repository.datasets.length) : unavailable, icon: Database, tone: "green" as const, description: "Detected assets" }]; return <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{values.map((item) => <StatCard key={item.label} {...item} />)}</div>; }

function executionTimeLabel(report: FinalVerificationReport | null, elapsedSeconds: number) { const value = report?.execution.execution_time; return typeof value === "number" ? `${value.toFixed(1)}s` : elapsedSeconds ? `${elapsedSeconds}s` : unavailable; }

function Pipeline({ events, report, currentStage }: { events: ExecutionEvent[]; report: FinalVerificationReport | null; currentStage: string }) { return <div className="overflow-x-auto pb-2"><div className="flex min-w-[920px] items-start">{pipeline.map(([label, stage], index) => { const event = events.find((item) => item.stage === stage); const complete = Boolean(event?.status === "SUCCESS" || (stage === "VERIFICATION_READY" && report)); const running = currentStage === stage || event?.status === "RUNNING"; const failed = event?.status === "FAILED"; return <div key={stage} className="flex flex-1 items-start"><div className="flex min-w-0 flex-1 flex-col items-center text-center"><div className={`relative flex h-10 w-10 items-center justify-center rounded-full border text-xs font-bold transition ${complete ? "border-emerald-400/40 bg-emerald-400/15 text-emerald-300" : failed ? "border-rose-400/40 bg-rose-400/15 text-rose-300" : running ? "border-violet-400/60 bg-violet-500/20 text-violet-200 shadow-lg shadow-violet-500/20" : "border-white/10 bg-white/[0.04] text-slate-600"}`}>{complete ? <CheckCircle2 className="h-4 w-4" /> : failed ? <XCircle className="h-4 w-4" /> : index + 1}</div><p className="mt-3 text-xs font-semibold text-slate-300">{label}</p><p className={`mt-1 text-[10px] uppercase tracking-wider ${complete ? "text-emerald-400" : failed ? "text-rose-400" : running ? "text-violet-300" : "text-slate-600"}`}>{complete ? "Complete" : failed ? "Failed" : running ? "Running" : "Pending"}</p></div>{index < pipeline.length - 1 && <div className={`mt-5 h-px flex-1 ${complete ? "bg-emerald-400/50" : "bg-white/10"}`} />}</div>; })}</div></div>; }

function RepositoryOverview({ repository, loading, dependencyFiles }: { repository: RepositoryMetadata | null; loading: boolean; dependencyFiles: string[] }) { const rows = [["Repository", repository?.repository_name], ["Framework", repository?.detected_frameworks[0]], ["Language", repository?.detected_languages[0]], ["Python version", undefined], ["Repository size", undefined], ["Files", repository ? `${repository.total_files} files` : undefined], ["Dependencies", dependencyFiles.length ? `${dependencyFiles.length} manifest(s)` : undefined], ["Datasets", repository ? `${repository.datasets.length} detected` : undefined], ["License", repository?.important_files.some((file) => /license|copying/i.test(file)) ? "Detected" : undefined], ["Docker", repository?.important_files.some((file) => /docker/i.test(file)) ? "Detected" : undefined], ["README", repository?.important_files.some((file) => /readme/i.test(file)) ? "Detected" : undefined]]; return <RepositoryCard><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">Repository intelligence</p><h2 className="mt-1 text-base font-semibold text-white">Repository overview</h2></div>{loading && <LoadingSpinner size="sm" />}</div><div className="grid gap-x-5 gap-y-4 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="border-b border-white/[0.06] pb-3"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-600">{label}</p><p className="mt-1 truncate text-sm font-medium text-slate-200">{value ?? unavailable}</p></div>)}</div></RepositoryCard>; }

function AIInsights({ analysis, report }: { analysis: RepositoryAIAnalysis | null; report: FinalVerificationReport | null }) { return <AIInsightCard title="AI insights"><div className="rounded-xl border border-violet-400/20 bg-violet-500/[0.07] p-4"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-violet-500/20 text-violet-200"><Sparkles className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-violet-100">Executive signal</p><p className="mt-2 text-sm leading-6 text-slate-300">{analysis?.summary ?? report?.explanation ?? unavailable}</p></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Insight label="Root cause" value={report?.troubleshooting?.root_cause ?? unavailable} /><Insight label="AI Confidence" value={report ? `${report.confidence}%` : unavailable} /><Insight label="Recommendation" value={report?.troubleshooting?.possible_fixes[0] ?? unavailable} /><Insight label="Estimated fix time" value={unavailable} /></div></AIInsightCard>; }
function Insight({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-600">{label}</p><p className="mt-1 line-clamp-2 text-sm text-slate-300">{value}</p></div>; }

function ExecutionTimeline({ events, history }: { events: ExecutionEvent[]; history: NonNullable<FinalVerificationReport["execution_history"]> }) { const items = [...events.map((event) => ({ title: event.stage.replaceAll("_", " "), detail: `${event.message} · ${new Date(event.timestamp).toLocaleTimeString()}`, status: event.status })), ...history.map((entry) => ({ title: `Attempt ${entry.attempt_number}`, detail: `${entry.reason} · ${entry.duration.toFixed(2)}s`, status: entry.execution_status }))]; return <div className="max-h-[390px] overflow-auto pr-2">{items.length ? <Timeline items={items} /> : <EmptyState icon={Clock3} text="Run verification to populate the execution timeline." />}</div>; }

function PatchSummary({ patch }: { patch: FinalVerificationReport["generated_patch"] }) { return <PatchCard><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500">Self-healing</p><h2 className="mt-1 text-base font-semibold text-white">Patch summary</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><PatchMetric icon={FileCode2} label="Files changed" value={patch ? String(patch.changed_files.length) : unavailable} /><PatchMetric icon={ShieldAlert} label="Risk" value={patch?.risk_level ?? unavailable} /><PatchMetric icon={Sparkles} label="Confidence" value={patch ? `${Math.round(patch.confidence * 100)}%` : unavailable} /><PatchMetric icon={Gauge} label="Success probability" value={patch ? `${Math.round(patch.estimated_success * 100)}%` : unavailable} /><PatchMetric icon={FileText} label="Patch size" value={patch?.git_unified_diff ? `${patch.git_unified_diff.length} chars` : unavailable} /></div>{patch && <p className="mt-4 rounded-xl border border-white/[0.07] bg-white/[0.03] p-3 text-xs leading-5 text-slate-400">{patch.summary}</p>}</PatchCard>; }
function PatchMetric({ icon: Icon, label, value }: { icon: typeof FileCode2; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-white/[0.03] p-3"><Icon className="h-4 w-4 text-violet-300" /><div><p className="text-[10px] uppercase tracking-[0.12em] text-slate-600">{label}</p><p className="mt-1 text-sm font-semibold text-slate-200">{value}</p></div></div>; }

function ActivityFeed({ items }: { items: { label: string; detail: string; status: string; timestamp: string }[] }) { return <div className="space-y-3">{items.length ? items.slice(-8).reverse().map((item, index) => <div key={`${item.timestamp}-${index}`} className="flex items-center gap-3 rounded-xl border border-white/[0.06] bg-white/[0.025] p-3"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${item.status === "FAILED" ? "bg-rose-400/10 text-rose-300" : item.status === "SUCCESS" || item.status === "COMPLETED" ? "bg-emerald-400/10 text-emerald-300" : "bg-violet-400/10 text-violet-300"}`}><Activity className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium capitalize text-slate-200">{item.label}</p><p className="truncate text-xs text-slate-600">{item.detail}</p></div><time className="text-[10px] text-slate-600">{new Date(item.timestamp).toLocaleTimeString()}</time></div>) : <EmptyState icon={Activity} text="No recent activity yet." />}</div>; }

function QuickActions({ repositoryId, onRun, isRunning }: { repositoryId?: string; onRun: () => void; isRunning: boolean }) { return <QuickActionPanel><Link href="/" className="action-button"><Upload className="h-4 w-4" /> Upload repository</Link><button type="button" onClick={onRun} disabled={!repositoryId || isRunning} className="action-button disabled:cursor-not-allowed disabled:opacity-40"><Play className="h-4 w-4" /> {isRunning ? "Running" : "Run again"}</button><Link href={repositoryId ? `/report/${repositoryId}` : "/analytics"} className="action-button"><FileText className="h-4 w-4" /> Generate report</Link><Link href="/analytics" className="action-button"><ArrowUpRight className="h-4 w-4" /> Analytics</Link><Link href="/troubleshooting" className="action-button"><Wrench className="h-4 w-4" /> Troubleshooting</Link></QuickActionPanel>; }

function FooterStats({ repository, analysis, report, uploads }: { repository: RepositoryMetadata | null; analysis: RepositoryAIAnalysis | null; report: FinalVerificationReport | null; uploads: import("@/types").UploadSummary[] }) { const stats = [["Repositories analysed", uploads.length ? String(uploads.length) : unavailable], ["Executions", report ? "1" : unavailable], ["AI diagnoses", report?.troubleshooting ? "1" : unavailable], ["Generated patches", report?.generated_patch ? "1" : unavailable], ["Successful fixes", report?.applied_patch && report.execution.success ? "1" : unavailable], ["Average runtime", executionTimeLabel(report, 0)]]; return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{stats.map(([label, value]) => <div key={label}><p className="text-[10px] uppercase tracking-[0.12em] text-slate-600">{label}</p><p className="mt-2 text-lg font-semibold text-slate-200">{value}</p></div>)}</div>; }
function EmptyState({ icon: Icon, text }: { icon: typeof Activity; text: string }) { return <div className="flex items-center gap-2 py-6 text-xs text-slate-600"><Icon className="h-4 w-4" />{text}</div>; }
function friendlyStatus(status: string, running: boolean) { if (running) return "Running"; if (status === "COMPLETED" || status === "SUCCESS") return "Completed"; if (status === "FAILED") return "Failed"; return "Idle"; }
function statusTone(status: string, running: boolean) { return running ? "warning" : status === "FAILED" ? "error" : status === "COMPLETED" || status === "SUCCESS" ? "success" : "neutral"; }
